version: "3"
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: "apilocalhost"
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - db
    command: >
      sh -c "/wait-for-it.sh db:3306 -- java -jar app.jar"

volumes:
  db:
    driver: local
